apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: quarkus-grpc-knative
spec:
  template:
    spec:
      containers:
        - image: <your-container-image>
          ports:
            - containerPort: 8080